// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBvv6ZdX6EVg6SfxqHBRwKFqtGJ0qYNlKw',
//     appId: '1:113964156128:web:ef1b23aeb668051a3afc85',
//     messagingSenderId: '113964156128',
//     projectId: 'push-notification-2f69f',
//     authDomain: 'push-notification-2f69f.firebaseapp.com',
//     storageBucket: 'push-notification-2f69f.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDjKl1dPxUfKtp3KEIC9WOdNltzr0k74a0',
//     appId: '1:113964156128:android:65bec2ba4b1e9a9d3afc85',
//     messagingSenderId: '113964156128',
//     projectId: 'push-notification-2f69f',
//     storageBucket: 'push-notification-2f69f.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAH8KXScXutBN6vCYMDTuAZUUqX_oLt1zA',
//     appId: '1:113964156128:ios:4e707fa0622e26f03afc85',
//     messagingSenderId: '113964156128',
//     projectId: 'push-notification-2f69f',
//     storageBucket: 'push-notification-2f69f.appspot.com',
//     androidClientId: '113964156128-ohk35u6m38q6ntudbcoe3i2lg2mf801d.apps.googleusercontent.com',
//     iosBundleId: 'com.salah.trigger_app',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAH8KXScXutBN6vCYMDTuAZUUqX_oLt1zA',
//     appId: '1:113964156128:ios:ab5ada0e0d5f21de3afc85',
//     messagingSenderId: '113964156128',
//     projectId: 'push-notification-2f69f',
//     storageBucket: 'push-notification-2f69f.appspot.com',
//     androidClientId: '113964156128-ohk35u6m38q6ntudbcoe3i2lg2mf801d.apps.googleusercontent.com',
//     iosBundleId: 'com.salah.trigger_app.RunnerTests',
//   );
// }
